#!/usr/bin/env node
// Builds assets/icons/sprite.svg from pinned Lucide icons (ISC). Run: node tools/build-sprite.mjs
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const LUCIDE_VERSION = '1.48.0';
const SOURCE = `https://cdn.jsdelivr.net/npm/lucide-static@${LUCIDE_VERSION}/icons`;
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'assets/icons/sprite.svg');

export const ICONS = [
  'arrow-down', 'arrow-left', 'arrow-right', 'arrow-up', 'armchair', 'ban', 'banknote',
  'calendar', 'calendar-clock', 'calendar-plus', 'chart-column', 'check', 'chevron-down',
  'chevron-left', 'chevron-right', 'circle-alert', 'circle-check', 'circle-play', 'circle-user-round',
  'circle-x', 'clock', 'credit-card', 'external-link', 'eye', 'eye-off', 'file-chart-column', 'flag',
  'goal', 'house', 'image', 'info', 'languages', 'list-filter', 'lock', 'log-in', 'log-out',
  'mail', 'map-pin', 'menu', 'message-circle', 'minus', 'monitor', 'moon', 'octagon-alert', 'pause',
  'pencil', 'play', 'plus', 'radio', 'refresh-cw', 'search', 'send', 'shield', 'shirt', 'star',
  'sun', 'table-2', 'thumbs-up', 'ticket', 'timer', 'trash-2', 'trending-down', 'trending-up',
  'triangle-alert', 'trophy', 'tv', 'user', 'user-plus', 'users', 'whistle', 'wifi-off', 'x',
];

export function toSymbol(name, svg) {
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s*\n\s*/g, '')
    .replace(/\s+\/>/g, '/>')
    .trim();
  return `<symbol id="i-${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">${inner}</symbol>`;
}

async function main() {
  const symbols = [];
  for (const name of ICONS) {
    const res = await fetch(`${SOURCE}/${name}.svg`);
    if (!res.ok) throw new Error(`Icon "${name}" not found (${res.status})`);
    symbols.push(toSymbol(name, await res.text()));
  }
  const sprite = [
    `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true">`,
    `<!-- Lucide icons v${LUCIDE_VERSION} (ISC License, https://lucide.dev). Generated by tools/build-sprite.mjs; do not edit by hand. -->`,
    ...symbols,
    `</svg>`,
    '',
  ].join('\n');
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, sprite, 'utf8');
  console.log(`Wrote ${ICONS.length} icons to ${OUT}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exitCode = 1;
});
